-- ==========================================================
-- PROJETO: GESTÃO DE RECURSOS HUMANOS (ENTERPRISE RH)
-- DESENVOLVIDO VIA VS CODE + TESTADO EM ORACLE 21C XE
-- ==========================================================

-- 1. CONFIGURAÇÃO DE SESSÃO PARA SCRIPTS LOCAIS
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

-- 2. CARGA DE DADOS DOS COLABORADORES
-- Inserindo 20 funcionários de uma vez (Simulando carga de DW)
INSERT ALL
  INTO EMPRESA_RH.FUNCIONARIOS VALUES (102, 'ANA SILVA', 4500.00, 1)
  INTO EMPRESA_RH.FUNCIONARIOS VALUES (103, 'CARLOS OLIVEIRA', 3200.00, 2)
  INTO EMPRESA_RH.FUNCIONARIOS VALUES (104, 'MARINA COSTA', 5100.00, 3)
  INTO EMPRESA_RH.FUNCIONARIOS VALUES (105, 'RICARDO SOUZA', 2800.00, 4)
  INTO EMPRESA_RH.FUNCIONARIOS VALUES (106, 'BEATRIZ LIMA', 3900.00, 5)
  INTO EMPRESA_RH.FUNCIONARIOS VALUES (107, 'FERNANDO ALVES', 4200.00, 1)
  INTO EMPRESA_RH.FUNCIONARIOS VALUES (108, 'JULIANA PEREIRA', 3100.00, 2)
  INTO EMPRESA_RH.FUNCIONARIOS VALUES (109, 'ROBERTO DIAS', 6000.00, 3)
  INTO EMPRESA_RH.FUNCIONARIOS VALUES (110, 'CAMILA ROCHA', 2700.00, 4)
  INTO EMPRESA_RH.FUNCIONARIOS VALUES (111, 'GABRIEL SANTOS', 3500.00, 5)
  INTO EMPRESA_RH.FUNCIONARIOS VALUES (112, 'AMANDA MARTINS', 4800.00, 1)
  INTO EMPRESA_RH.FUNCIONARIOS VALUES (113, 'LUCAS FERREIRA', 3300.00, 2)
  INTO EMPRESA_RH.FUNCIONARIOS VALUES (114, 'PATRICIA GOMES', 5500.00, 3)
  INTO EMPRESA_RH.FUNCIONARIOS VALUES (115, 'BRUNO CARVALHO', 2900.00, 4)
  INTO EMPRESA_RH.FUNCIONARIOS VALUES (116, 'LARISSA MENDES', 3700.00, 5)
  INTO EMPRESA_RH.FUNCIONARIOS VALUES (117, 'IGOR PINTO', 4100.00, 1)
  INTO EMPRESA_RH.FUNCIONARIOS VALUES (118, 'VANESSA LOPES', 3000.00, 2)
  INTO EMPRESA_RH.FUNCIONARIOS VALUES (119, 'THIAGO BARBOSA', 6200.00, 3)
  INTO EMPRESA_RH.FUNCIONARIOS VALUES (120, 'NICOLE RIBEIRO', 2600.00, 4)
  INTO EMPRESA_RH.FUNCIONARIOS VALUES (121, 'DANILO SANTIAGO', 3400.00, 5)
SELECT * FROM DUAL;

COMMIT;

-- 3. RELATÓRIO ANALÍTICO DE FOLHA DE PAGAMENTO
-- Cruzando departamentos com a soma dos salários
SELECT 
    d.NOME_DEP AS DEPARTAMENTO, 
    COUNT(f.ID_FUNC) AS TOTAL_PESSOAS,
    'R$ ' || TO_CHAR(SUM(f.SALARIO), '999G999D00') AS CUSTO_MENSAL
FROM EMPRESA_RH.DEPARTAMENTOS d
LEFT JOIN EMPRESA_RH.FUNCIONARIOS f ON d.ID_DEP = f.ID_DEP
GROUP BY d.NOME_DEP
ORDER BY SUM(f.SALARIO) DESC;
