ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

INSERT ALL
  INTO EMPRESA_RH.FUNCIONARIOS VALUES (102, 'ANA SILVA', 4500.00, 1)
  INTO EMPRESA_RH.FUNCIONARIOS VALUES (103, 'CARLOS OLIVEIRA', 3200.00, 2)
 
SELECT * FROM DUAL;

COMMIT;

SELECT d.NOME_DEP, SUM(f.SALARIO) AS TOTAL_FOLHA
FROM EMPRESA_RH.DEPARTAMENTOS d
INNER JOIN EMPRESA_RH.FUNCIONARIOS f ON d.ID_DEP = f.ID_DEP
GROUP BY d.NOME_DEP;
