BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE MEUS_CACTOS';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE MEUS_CACTOS (
    ID_CACTO NUMBER PRIMARY KEY,
    NOME_POPULAR VARCHAR2(100),
    ESPECIE VARCHAR2(100),
    DATA_AQUISICAO DATE,
    TIPO_VASO VARCHAR2(50)
);

INSERT INTO MEUS_CACTOS VALUES (1, 'Orelha de Mickey', 'Opuntia microdasys', TO_DATE('2026-01-15', 'YYYY-MM-DD'), 'Redondo');
INSERT INTO MEUS_CACTOS VALUES (2, 'Coroa de Frade', 'Melocactus zehntneri', TO_DATE('2026-02-10', 'YYYY-MM-DD'), 'Barro');
INSERT INTO MEUS_CACTOS VALUES (3, 'Rabo de Macaco', 'Hildewintera colademononis', TO_DATE('2026-03-01', 'YYYY-MM-DD'), 'Parede');

COMMIT;

SELECT NOME_POPULAR, TIPO_VASO 
FROM MEUS_CACTOS 
ORDER BY TIPO_VASO;
